<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Content.StyleSheetify.Client</RootNamespace>
    </PropertyGroup>
    
    <Import Project="../../MSBuild/Content.props" />

    <Import Project="..\..\RobustToolbox\Imports\Client.props" />
    <Import Project="..\..\RobustToolbox\Imports\Shared.props" />

    <Import Project="..\..\RobustToolbox\MSBuild\Robust.Properties.targets" />

    <ItemGroup>
      <ProjectReference Include="..\Content.StyleSheetify.Shared\Content.StyleSheetify.Shared.csproj" />
    </ItemGroup>
    
</Project>
