<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <Import Project="../../MSBuild/Content.props" />

    <ItemGroup>
      <ProjectReference Include="..\Content.StyleSheetify.Shared\Content.StyleSheetify.Shared.csproj" />
    </ItemGroup>

    <Import Project="..\..\RobustToolbox\MSBuild\Robust.Properties.targets" />
    <Import Project="..\..\RobustToolbox\Imports\Shared.props" />
</Project>
