<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Content.StyleSheetify.Shared</RootNamespace>
    </PropertyGroup>

    <Import Project="../../MSBuild/Content.props" />
    
    <ItemGroup>
        <PackageReference Include="YamlDotNet" />
    </ItemGroup>

    <Import Project="..\..\RobustToolbox\Imports\Lidgren.props" />
    <Import Project="..\..\RobustToolbox\Imports\Shared.props" />

    <Import Project="..\..\RobustToolbox\MSBuild\Robust.Properties.targets" />
    <Import Project="..\..\RobustToolbox\MSBuild\Robust.CompNetworkGenerator.targets" />
</Project>
